apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\WINDOWS\system32\kompose.exe convert -f docker-compose-resolved.yaml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: user-service
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\WINDOWS\system32\kompose.exe convert -f docker-compose-resolved.yaml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: user-service
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: library
            - name: POSTGRES_HOST
              value: database
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: user
            - name: RABBITMQ_DEFAULT_PASS
              value: guest
            - name: RABBITMQ_DEFAULT_PASSWORD
              value: guest
            - name: RABBITMQ_DEFAULT_USER
              value: guest
          image: dimple295/user_service:1.0
          name: api
          ports:
            - containerPort: 5002
              protocol: TCP
      restartPolicy: Always
